### PR TITLE
server: add server startup message

### PR DESCRIPTION
**Pull request by aead**
This commit adds a `-q, --quiet` flag to the
`kes server` command.

If not specified the server now prints a startup
message that contains the server endpoint(s),
root identity, key store location a.s.o.

If the `-q` flag is specified the server does
not print a startup message and behaves as before.

### CODE REVIEW

**Comment by aead** [comment]
Screenshot from 2020-07-13 15-28-55

**Comment by harshavardhana** [comment]
If you have lots of local IPs @aead we will take up a lot of space writing it in one line would be sufficient IMO 

> Endpoint:  http://10.0.0.67:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000          

Can the CLI also be written in one line? @aead - currently I can copy-paste it properly 

What is the use for displaying `Root:` for the client? @aead

**Comment by aead** [comment]
> If you have lots of local IPs @aead we will take up a lot of space writing it in one line would be sufficient IMO

The problem with one line is that if you have lots of IPs or don't have a small terminal window (not full screen) the IPs wrap at the line ending which looks really weird. Instead what I can do is write in one line until it would wrap, and then, start a new properly aligned line. Like:
```
Endpoint: https://<IP>:<port>    https://<IP>:<port>   https://<IP>:<port>
          https://<IP>:<port>    https://<IP>:<port>
```

> Can the CLI also be written in one line? @aead - currently I can't copy-paste it properly

You have to edit it anyway, right?! Are you saying have the CLI like:
```
CLI:     export KES_SERVER=https://<ip>:<port> KES_CLIENT_KEY=<client-key> KES_CLIENT_CERT=<client-cert>
```
Again, here it's slightly easier to copy-paste but I cannot properly document for new users (see the `// e.g.` comment)
and there is a again the line wrapping issue.

> What is the use for displaying Root: for the client?

To display who is root and whether a root identity is present or not. If you e.g. start the server with `--root=_`
the you get:
```
Root:     _     [ disabled ]
```

Root in KES is like MinIO admin - so a user may want to see on startup who / whether there is root.

**Comment by aead** [comment]
@harshavardhana PTAL at the list of endpoints [here](https://github.com/minio/kes/pull/66#issuecomment-657564313). Now, there are two endpoints per line. Let me know whether that is acceptable for you.

**Pull request merged**
