### PR TITLE
update prometheus dependency

### PR DESCRIPTION
**Pull request by harshavardhana**
This is mainly needed for https://github.com/minio/mcc kes client 
dependency,  to avoid some cross dependencies with etcd.

### CODE REVIEW

**Comment by aead** [comment]
You are deleting the `go.sum` file. Can you include the updated `go.sum` in the PR?

**Comment by harshavardhana** [comment]
> You are deleting the `go.sum` file. Can you include the updated `go.sum` in the PR?

Where it's just updated with `go mod tidy` @aead

**Comment by harshavardhana** [comment]
> You are deleting the `go.sum` file. Can you include the updated `go.sum` in the PR?

PTAL need this for mcc project

**Review by aead — APPROVED** [review]

**Comment by aead** [comment]
Oh sry, seemed like `go.sum` got deleted. Merged.

**Pull request merged**
