### PR TITLE
vault-self-signed-support - adds support for vault using a self signe…

### PR DESCRIPTION
**Pull request by Alevsk**
…d certificate by adding the insecure configuration

### CODE REVIEW

**Comment by harshavardhana** [comment]
We shouldn't be using insecure mode, is there a good reason to provide this option?

**Comment by Alevsk** [comment]
> We shouldn't be using insecure mode, is there a good reason to provide this option?

We need to use kes and vault with a self signed certificate for testing in our local environments, I'll talk with @aead to see if there's an alternative on how to do this.

**Comment by aead** [comment]
@Alevsk Closing this b/c a) already supported via https://github.com/minio/kes/blob/master/server-config.toml#L123 and b) we should never skip the X.509 certificate trust chain checks. Either disable TLS  (local testing) or role out PKI/direct trust in production.

**Comment by Alevsk** [comment]
Thanks for the clarification @aead

**Pull request closed without merging**
