### PR TITLE
edge: fix recursion bug in iterator

### PR DESCRIPTION
**Pull request by aead**
This commit fixes a recursion bug in the iterator
implementation.

### CODE REVIEW

**Review by klauspost — APPROVED** [review]
Ouch.

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by klauspost** [comment]
@aead May I recommend adding [staticcheck](https://staticcheck.io/) to CI?

It catches these:
```
test.go:12:9: infinite recursive call (SA5007)
```

**Comment by aead** [comment]
@klauspost Will add that in a separate PR - which probably will fix a series of hints 👍

**Pull request merged**
