### PR TITLE
add HMAC API test

### PR DESCRIPTION
**Pull request by aead**
This commit adds tests for the HMAC server API.
It also removes enclave code that is no longer used nor supported.

Requires minio/kms-go#9

### CODE REVIEW

**Comment by shtripat** [comment]
Do we need go.mod changes for kes-go to clear of build fails?

**Comment by aead** [comment]
As the commit/PR message says, we need to merge minio/kms-go#9 first and then update the go mod dependency.

**Comment by aead** [comment]
SDK PR is merged 🎉

**Review by shtripat — APPROVED** [review]
lgtm

**Pull request merged**
