### PR TITLE
Fix name of application

### PR DESCRIPTION
**Pull request by ramondeklein**
I guess the name of the application should be `kes` everywhere.

### CODE REVIEW

**Review by shtripat — APPROVED** [review]
lgtm, please check the build failures.

**Review by harshavardhana — APPROVED** [review]
I prefer os.Args[0] but this is acceptable

**Comment by ramondeklein** [comment]
@harshavardhana I do to, but I wanted to bring it inline with the rest of the application. Search for `$ kes ` and there are lots of references. Just wanted to fix this incorrect one.

**Comment by ramondeklein** [comment]
@harshavardhana Can you merge. I'm not allowed to...

**Comment by klauspost** [comment]
@ramondeklein Seems like [CI](https://github.com/minio/kes/blob/master/.github/workflows/go.yml) needs a version bump :/

**Comment by ramondeklein** [comment]
@klauspost I'll know how to do that :wink:

**Comment by ramondeklein** [comment]
@klauspost Can you merge?

**Comment by ramondeklein** [comment]
@aead Can you merge?

**Review by aead — APPROVED** [review]

**Pull request merged**
